skipped html-webpack-plugin upgrade
May be html-webpack-plugin is related to webpack package hence will upgrade with webpack itself. Because it is showing some error as follows:
TypeError: Cannot read property 'tap' of undefined
    at HtmlWebpackPlugin.apply (/home/abhinandan/github/care_fe/node_modules/html-webpack-plugin/index.js:40:31)
    at webpack (/home/abhinandan/github/care_fe/node_modules/webpack/lib/webpack.js:51:13)
    at startDevServer (/home/abhinandan/github/care_fe/node_modules/webpack-dev-server/bin/webpack-dev-server.js:94:16)
    at /home/abhinandan/github/care_fe/node_modules/webpack-dev-server/bin/webpack-dev-server.js:166:3
    at /home/abhinandan/github/care_fe/node_modules/webpack-dev-server/lib/utils/processOptions.js:33:9